### ISSUE TITLE
`yarn run mirrorful` didn't work in monorepo

### ISSUE THREAD

**Issue by cruxcode** [Mirrorful/mirrorful#45]
Log:

```
yarn run v1.22.18
$ /Users/shyamswaroop/projects/cruxcode/atrilabs-engine/node_modules/.bin/mirrorful
Running Mirrorful version: 2.0.5
Starting Mirrorful in /Users/shyamswaroop/projects/cruxcode/atrilabs-engine/packages/example-atri-app.

Error: ENOENT: no such file or directory, chdir '/Users/shyamswaroop/projects/cruxcode/atrilabs-engine/packages/example-atri-app' -> 'node_modules/mirrorful/editor'
    at process.wrappedChdir [as chdir] (node:internal/bootstrap/switches/does_own_process_state:112:14)
    at /Users/shyamswaroop/projects/cruxcode/atrilabs-engine/node_modules/mirrorful/dist/init.js:35:21
    at Generator.next (<anonymous>)
    at fulfilled (/Users/shyamswaroop/projects/cruxcode/atrilabs-engine/node_modules/mirrorful/dist/init.js:5:58) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'chdir',
  path: '/Users/shyamswaroop/projects/cruxcode/atrilabs-engine/packages/example-atri-app',
  dest: 'node_modules/mirrorful/editor'
}
```

**Comment by alexdanilowicz** [comment]
Thanks for making this issue! Fixed this in my last PR, will open up a PR against AtriLabs shortly!
